# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7f37737a4c7db06fad1e2ea3f2969c44ef0a7b97cf7738a1b6f950f50e7dd47b16464fcf186471225964de90b7649d2a88f48b87194c3103eab178a2b9b26af

test:
  secret_key_base: 620719c318b26377ada72b444ca32cd3746914758dbbf5f7e65f86c0badf6da8aa1be2ccf8d024a8283e973f0ee5a8c019295d0aeb71c68304c1acfe95a894f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
